project:
  type: website
  output-dir: docs

website:
  title: "Pritam Dey"
  favicon: images/hhhh-modified.png
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bio.qmd
        text: Bio
      - href: research.qmd
        text: Research
      - href: CV.pdf
        text: CV
    right:
      - icon: github
        href: https://github.com/pritamdey
        aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com/in/pritamdey1906
        aria-label: LinkedIn
      - icon: envelope-at-fill
        href: mailto:pritam.dey@tamu.edu
        aria-label: Email


format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

